# foosnapper.conf - Foosnapper, automatic filesystem snapshotter.

### Stratis example:
#
# [myhost home]       # pool_name filesystem_name
#
# interval = 20       # minutes
# keep = 10           # number of snapshots to keep

### BTRFS example:
#
# [btrfs home]        # subvolume "home" mounted to "/home"
#
# interval = 20
# keep = 10
#
# [btrfs root]        # subvolume "root" mounted to "/"
#
# path = /
# interval = 20
# keep = 10
#
# [btrfs myuser]      # subvolume "myuser" mounted to "/home/myuser"
#
# path = /home/myuser
# interval = 20
# keep = 10
