# foosnapper.conf - Foosnapper, automatic filesystem snapshotter.


### BTRFS examples ###


### Subvolume "home" mounted to "/home".
#
# [btrfs home]
#
# interval = 20       # Minutes
# keep = 10           # Number of snapshots to keep

### Subvolume "root" mounted to "/". Path (mountpount) must be specified as
### it defaults to "/subvolume-name".
#
# [btrfs root]
#
# path = /
# interval = 20
# keep = 10

### Subvolume "myuser" mounted to "/home/myuser".
#
# [btrfs myuser]
#
# path = /home/myuser
# interval = 20
# keep = 10

### Subvolume "mydata" mounted to "/srv/data". Store snapshots to
### "/srv/foosnapper" instead of default "/media/foosnapper".
#
# [btrfs mydata]
#
# path = /srv/mydata
# storage = /srv/foosnapper
# interval = 20
# keep = 10


### Stratis example ###


# [myhost home]       # pool_name filesystem_name
#
# interval = 20
# keep = 10
